---
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart dod-source
  service:
    name: dod-source
    state: restarted
  listen: "Restart source games"

- name: Stop dod-source
  service:
    name: dod-source
    state: stopped
  listen: "Stop source games"
